config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:create] do
    post :admin_create, on: :collection
  end

  resources :events do
    resources :roles
    resources :attendees do
      collection do
        get :import
        post :import, to: "import#attendees"
        post :export
        post :export_blanks
      end

      member do
        post :check_in
      end
    end
  end

  root to: "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :events

  validates :first_name, :last_name, presence: true

  def name
    [first_name, last_name].join(" ")
  end

  def self.alphabetical
    order("last_name asc, first_name asc")
  end

  def name
    [first_name, last_name].join(" ")
  end

  def role
    if admin || super_admin
      "Admin"
    else
      "Standard"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize!
  before_action :authorize_super_admin!
  before_action :find_user, only: [:edit, :update, :destroy]

  def index
    @users = User.alphabetical
  end

  def new
    @user = User.new
  end

  def admin_create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :admin, :manager, :event_ids, event_ids: [])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = "Successfully updated user."
      redirect_to users_path
    else
      flash[:alert] = "Unable to update user."
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = "Successfully removed user #{@user.name}."
      redirect_to users_path
    else
      flash[:alert] = "Unable to remove user #{@user.name}."
      redirect_to users_path
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :super_admin, :admin)
  end
end

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <p class="alert">Unable to create user.
  <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  </p>
<% end %>

<%= form_for(user, url: admin_create_users_path) do |f| %>
  <div class="twogroups">
    <div>
      <%= f.label :first_name %>
    </div>
    <div>
      <%= f.text_field :first_name, autofocus: true %>
    </div>
  </div>

  <div class="twogroups">
    <div>
      <%= f.label :last_name %>
    </div>
    <div>
      <%= f.text_field :last_name %>
    </div>
  </div>

  <div class="twogroups">
    <div>
      <%= f.label :email, "Email Address" %>
    </div>
    <div>
      <%= f.email_field :email %>
    </div>
  </div>

  <div class="twogroups">
    <div>
      <%= f.label :password, "Password" %>
    </div>
    <div>
      <%= f.password_field :password %>
    </div>
  </div>

  <div class="twogroups">
    <div>
      <%= f.label :password_confirmation, "Password Confirmation" %>
    </div>
    <div>
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <div class="twogroups">
    <div><label>Permissions</label></div>
    <% if current_user.admin %>
      <div>
        <%= f.check_box :admin %>
        <%= f.label :admin %>
        <%= f.check_box :manager %>
        <%= f.label :manager %>
      </div>
    <% end %>
  </div>

  <div class="twogroups">
    <div><%= f.label :event_ids, "Events" %></div>
    <div>
      <%= collection_check_boxes :user, :event_ids, Event.alphabetical, :id, :name, {}, class: "test"  %>
    </div>
  </div>
  <div class="twogroups">
    <div></div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<nav class="righthand-nav">
  <%= link_to "Add User", new_user_path, class: "btn btn-primary" %>
</nav>
<h1>User Accounts</h1>

<%= link_to "Add User", new_user_path %>

<table>
  <thead>
    <th>Name</th>
    <th>Email</th>
    <th>Events</th>
    <th>Role</th>
    <th></th>
  </thead>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.events.pluck(:name).join(", ") %></td>
      <td><%= user.role %></td>
      <td class="actions">
        <%= link_to "Edit", edit_user_path(user) %>
        <% if current_user.admin %>
          <%= link_to "Delete", user_path(user), method: :delete %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Add User</h1>
<%= render "form", user: @user %>