config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:create] do
    post :admin_create, on: :collection
  end

  resources :events do
    resources :roles
    resources :attendees do
      collection do
        get :import
        post :import, to: "import#attendees"
        post :export
        post :export_blanks
      end

      member do
        post :check_in
      end
    end
  end

  root to: "home#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :logo, LogoUploader

  has_and_belongs_to_many :users
  has_many :roles
  has_many :attendees
  has_many :sponsor_companies

  scope :upcoming, -> { order(:start_date) }
  scope :alphabetical, -> { order(:name) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if current_user.admin
      @events = Event.upcoming
    else
      @events = current_user.events.upcoming
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    @event.users << current_user

    if @event.save
      redirect_to event_roles_path(@event)
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees.with_name(params[:first_name], params[:last_name])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :start_date, :end_date, :logo)
  end
end

app/views/events/_form.html.erb
<%= form_for event do |f| %>
  <div class="twogroups">
    <div>
      <%= f.label :name %><br />
    </div>
    <div>
      <%= f.text_field :name %>
    </div>
  </div>
  
  <div class="twogroups">
    <div>
      <%= f.label :start_date %><br />
    </div>
    <div>
      <%= f.date_field :start_date, class: "datepicker" %>
    </div>
  </div>

  <div class="twogroups">
    <div>
      <%= f.label :end_date %><br />
    </div>
    <div>
      <%= f.date_field :end_date, class: "datepicker" %>
    </div>
  </div>
  
  <div class="twogroups">
    <div>
      <%= f.label :logo %><br />
    </div>
    <div>
      <%= f.file_field :logo %>
    </div>
  </div>
  
  <div class="twogroups">
    <div></div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= render "form", event: @event %>

app/views/events/index.html.erb
<nav class="righthand-nav">
  <% if current_user.admin || current_user.manager %>
    <%= link_to "Add Event", new_event_path, class: "btn btn-primary" %>
  <% end %>
</nav>
<h1>Events</h1>

<table>
  <thead>
    <th>Name</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th></th>
  </thead>
  <% @events.each do |event| %>
    <tr>
      <td><%= link_to event.name, event_path(event) %></td>
      <td><%= l(event.start_date.to_date, format: :long) %></td>
      <td><%= l(event.end_date.to_date, format: :long) %></td>
      <td class="actions">
        <%= link_to "View Attendees", event_attendees_path(event) %>
        <%= link_to "Edit", edit_event_path(event) %>
        <% if current_user.admin %>
          <%= link_to "Delete", event_path(event), method: :delete %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>New Event</h1>
<%= render "form", event: @event %>

app/views/events/show.html.erb
<nav class="righthand-nav">
  <%= link_to "Import Attendees", import_event_attendees_path(@event), class: "btn btn-primary" %>
  <%= link_to "Add Attendee", new_event_attendee_path(@event), class: "btn btn-primary" %>
</nav>
<h1><%= @event.name %></h1>

<nav>
  <%= link_to "Roles", event_roles_path(@event) %>
  <%= link_to "Generate Badges", export_event_attendees_path(@event), method: :post, target: "_blank" %>
  <%= link_to "Generate Blanks", export_blanks_event_attendees_path(@event), method: :post, target: "_blank" %>
</nav>

<div>
  <%= form_tag event_path(@event), method: :get do %>
    <%= text_field_tag "first_name", params['first_name'], placeholder: "First Name"  %>
    <%= text_field_tag "last_name", params['last_name'], placeholder: "Last Name"  %>
    <%= submit_tag "Search", class: "btn btn-xs btn-secondary"  %>
  <% end %>
</div>
<table>
  <th></th>
  <th>First Name</th>
  <th>Last Name</th>
  <th>Email</th>
  <th>Role</th>
  <th>Company</th>
  <th>Twitter</th>
  <th></th>
  <% @attendees.includes(:role).alphabetical.each do |attendee| %>
    <tr>
      <td data-url=<%= check_in_event_attendee_path(@event, attendee) %> data-checked-in=<%= attendee.checked_in? %>>
        <%= fa_icon("check-square-o") %>
      </td>
      <td><%= attendee.first_name %></td>
      <td><%= attendee.last_name %></td>
      <td><%= attendee.email %></td>
      <td><%= attendee.role.name %></td>
      <td><%= attendee.company %></td>
      <td><%= attendee.twitter %></td>
      <td class="actions">
        <%= link_to "Edit", edit_event_attendee_path(@event, attendee) %>
        <%= link_to "Delete", event_attendee_path(@event, attendee), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>