config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:create] do
    post :admin_create, on: :collection
  end

  resources :events do
    resources :roles
    resources :attendees do
      collection do
        get :import
        post :import, to: "import#attendees"
        post :export
        post :export_blanks
      end

      member do
        post :check_in
      end
    end
  end

  root to: "home#index"
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :event
  has_many :attendees
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
  end

  def new
    @event = Event.find(params[:event_id])
    @role = @event.roles.new
  end

  def create
    @event = Event.find(params[:event_id])
    @role = @event.roles.build(role_params)

    if @role.save
      redirect_to event_roles_path(@event)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:event_id])
    @role = @event.roles.find(params[:id])
  end

  def update
    @event = Event.find(params[:event_id])

    if @event.roles.find(params[:id]).update(role_params)
      redirect_to event_roles_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:event_id])

    role = @event.roles.find(params[:id])
    role.destroy

    redirect_to event_roles_path(@event)
  end

  private

  def role_params
    params.require(:role).permit(:name, :reference_key, :border_color)
  end
end

app/views/roles/_form.html.erb
<%= form_for([event, role]) do |f| %>
<div class="twogroups">
  <div><%= f.label :name, value: "Role name" %></div>
  <div>
    <%= f.text_field :name, autofocus: true %>
  </div>
</div>

<div class="twogroups">
  <div><%= f.label :border_color, value: "Border Color" %></div>
  <div>
    <%= f.text_field :border_color, autofocus: true %>
  </div>
</div>

<div class="twogroups">
  <div><%= f.label :reference_key, value: "Reference Key" %></div>
  <div>
    <%= f.text_field :reference_key, autofocus: true %>
  </div>
</div>

<div class="twogroups">
  <div></div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/roles/edit.html.erb
<h1>Edit Role <small><%= link_to "#{@event.name} Roles", event_roles_path(@event) %></small></h1>

<% if @role.errors.any? %>
  <p class="alert">Unable to update role.
  <ul>
    <% @role.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  </p>
<% end %>

<%= render "form", event: @event, role: @role %>

app/views/roles/index.html.erb
<h1 class="page-title">Roles
  <small><%= link_to @event.name, event_path(@event) %></small>
  <%= link_to "Add Role", new_event_role_path(@event), class: "btn btn-primary pull-right" %>
</h1>

<% @event.roles.each do |role| %>
  <section>
    <h2><%= role.name.presence || "<No Role Display>"%></h2>
    <div class="preview">
      <div style="border: 10px solid #<%= role.border_color %>; height: 200px; width: 130px;">
        <%= image_tag @event.logo %>
        <div class="first">First</div>
        <div class="last">Last</div>
        <div class="role"><%= role.name %></div>
      </div>
    </div>
    <div class="info">
      <%= form_for [@event, role] do |f| %>
        <%= f.label :name do %>
          Role Display
          <%= f.text_field :name %>
        <% end %>
        <%= f.label :reference_key do %>
          CSV Role
          <%= f.text_field :reference_key %>
          <small>Key that corresponds to this role.</small>
        <% end %>
        <%= f.label :border_color do %>
          Badge Color
          <%= f.text_field :border_color %>
        <% end %>

        <%= f.submit "Update Role" %>
        <%= link_to "Remove", event_role_path(@event, role), method: :delete, confirm: "This action cannot be undone." %>
      <% end %>
    </div>
  </section>
<% end %>

app/views/roles/new.html.erb
<h1>Add Role <small><%= link_to "#{@event.name} Roles", event_roles_path(@event) %></small></h1>

<% if @role.errors.any? %>
  <p class="alert">Unable to create role.
  <ul>
    <% @role.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  </p>
<% end %>

<%= render "form", event: @event, role: @role %>