config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:create] do
    post :admin_create, on: :collection
  end

  resources :events do
    resources :roles
    resources :attendees do
      collection do
        get :import
        post :import, to: "import#attendees"
        post :export
        post :export_blanks
      end

      member do
        post :check_in
      end
    end
  end

  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Badger</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <a href="<%= events_path %>">
        <%= image_tag("badger.png") %>
      </a>

      <nav>
        <% if user_signed_in? && (current_user.admin || current_user.manager) %>
          <%= link_to "Accounts", users_path %>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to "Events", events_path %>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %>
        <% end %>
      </nav>
    </header>

    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>

    <footer>
      Badger App &copy; <%= link_to "Laura Mosher", "http://lauramosher.com" %>
    </footer>

    <%= javascript_include_tag 'application' %>
  </body>
</html>